export enum CompanyPersona {
  STARTUP = 'STARTUP',
  SCALEUP = 'SCALEUP',
  ENTERPRISE = 'ENTERPRISE',
  AGENCY = 'AGENCY',
  CONSULTING = 'CONSULTING',
  SAAS = 'SAAS',
  ECOMMERCE = 'ECOMMERCE',
  FINTECH = 'FINTECH',
  HEALTHCARE = 'HEALTHCARE',
  OTHER = 'OTHER',
}
