export enum ResearchStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  RESEARCH_RETRY_REQUIRED = 'RESEARCH_RETRY_REQUIRED',
  INSUFFICIENT = 'INSUFFICIENT',
  FAILED = 'FAILED',
}
